"""add document storage columns

The five columns ADR-0008 §4 assigns to the `Document` model, the two CHECK
constraints that keep them honest, and the partial unique index ADR-0010 relies
on. Migration 0001 left these out on purpose — "assigned to Milestone M3 by
ADR-0008 … and arrive with the code that writes them" — and M3/S3.1 is that code.

Autogenerated, then corrected: autogenerate did not emit the two CHECK
constraints, as docs/development/migrations.md warns it will not.

* **All five columns nullable.** Documents created before upload existed have
  no bytes anywhere, and NOT NULL would require inventing a storage key and a
  hash for them. Upload sets all five together.
* **`size_bytes > 0` and `page_count > 0`.** A NULL passes a CHECK, so rows
  without content are unaffected; an upload can never record a zero-byte or
  zero-page document.
* **`uq_documents_user_id_content_hash`**, unique on `(user_id, content_hash)`
  `WHERE deleted_at IS NULL`. One live document per owner per content. Partial,
  so a deleted document does not block uploading the same file again; and NULL
  hashes never conflict, so every existing row satisfies it.

Safe on a populated table: nullable ADD COLUMN with no default rewrites nothing
on PostgreSQL 11+. The unique index is the one statement that reads every row,
and it cannot fail on existing data, because no existing row has a hash.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-14 16:53:02.993783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, Sequence[str], None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the storage columns, their constraints, and the per-owner unique index."""
    op.add_column(
        "documents", sa.Column("storage_key", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "documents", sa.Column("content_hash", sa.String(length=64), nullable=True)
    )
    op.add_column("documents", sa.Column("size_bytes", sa.BigInteger(), nullable=True))
    op.add_column(
        "documents", sa.Column("mime_type", sa.String(length=255), nullable=True)
    )
    op.add_column("documents", sa.Column("page_count", sa.Integer(), nullable=True))

    op.create_check_constraint(
        op.f("ck_documents_size_bytes_positive"), "documents", "size_bytes > 0"
    )
    op.create_check_constraint(
        op.f("ck_documents_page_count_positive"), "documents", "page_count > 0"
    )

    op.create_index(
        "uq_documents_user_id_content_hash",
        "documents",
        ["user_id", "content_hash"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )


def downgrade() -> None:
    """Remove them again, in reverse.

    Destructive for uploaded documents: their storage keys and hashes go with
    the columns, and the rows that remain no longer say where their bytes are.
    The blobs themselves are untouched on disk. Downgrading past this revision
    in an environment with real uploads is a decision, not a routine step.
    """
    op.drop_index(
        "uq_documents_user_id_content_hash",
        table_name="documents",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_constraint(
        op.f("ck_documents_page_count_positive"), "documents", type_="check"
    )
    op.drop_constraint(
        op.f("ck_documents_size_bytes_positive"), "documents", type_="check"
    )
    op.drop_column("documents", "page_count")
    op.drop_column("documents", "mime_type")
    op.drop_column("documents", "size_bytes")
    op.drop_column("documents", "content_hash")
    op.drop_column("documents", "storage_key")
