"""initial schema — users, documents, document_chunks

The first persistent schema for ResearchMind. Establishes the three entities
ADR-0003 names as the system of record, and the ownership chain between them:

    users <-RESTRICT- documents <-CASCADE- document_chunks

Autogenerated, then reviewed line by line. Worth knowing when reading it:

* Every constraint and index is explicitly named via ``op.f()``, resolving the
  naming convention on ``Base.metadata``. This is what lets ``downgrade()``
  drop them by name.
* The enum columns are VARCHAR with a CHECK, not a PostgreSQL ENUM type. A
  native enum would survive ``drop_table`` as an orphaned type and have to be
  dropped separately — the classic reason a first migration is not reversible.
* ``documents`` carries no storage columns (``storage_key``, ``content_hash``,
  ``size_bytes``, ``mime_type``, ``page_count``) and ``document_chunks`` no
  section columns (``section``, ``page_start``, ``page_end``). Both sets are
  assigned to Milestone M3 by ADR-0008 and ADR-0007 respectively, and arrive
  with the code that writes them.
* No ``password_hash``. Authentication is M2, and a credential column here
  would encode a decision that milestone has not made.

Revision ID: 0001
Revises:
Create Date: 2026-09-12 17:48:13.990287

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the three tables, in foreign-key order."""
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "admin",
                "researcher",
                "viewer",
                name="user_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column(
            "doc_type",
            sa.Enum(
                "pdf",
                "text",
                "note",
                "report",
                name="document_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "ready",
                "error",
                name="document_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "chunk_count >= 0", name=op.f("ck_documents_chunk_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_documents_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        op.f("ix_documents_user_id_created_at"),
        "documents",
        ["user_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("embedding_model_id", sa.String(length=255), nullable=True),
        sa.Column("dimension", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chunk_index >= 0", name=op.f("ck_document_chunks_chunk_index_non_negative")
        ),
        sa.CheckConstraint(
            "dimension IS NULL OR dimension > 0",
            name=op.f("ck_document_chunks_dimension_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint(
            "document_id",
            "chunk_index",
            name=op.f("uq_document_chunks_document_id_chunk_index"),
        ),
    )


def downgrade() -> None:
    """Drop everything, in reverse foreign-key order.

    Returns the database to empty: no tables, and no leftover enum types,
    because the enums are CHECK constraints on VARCHAR columns rather than
    native PostgreSQL types.
    """
    op.drop_table("document_chunks")
    op.drop_index(
        op.f("ix_documents_user_id_created_at"),
        table_name="documents",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("documents")
    op.drop_table("users")
